# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [2]:
# your code goes here
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)

In [3]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  object
 2   State                          10279 non-null  object
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  object
 5   Coverage                       10910 non-null  object
 6   Education                      10910 non-null  object
 7   Effective To Date              10910 non-null  object
 8   EmploymentStatus               10910 non-null  object
 9   Gender                         10910 non-null  object
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  object
 12  Marital Status                 10910 non-null  object
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  object
 19  Policy                         10910 non-null  object
 20  Renew Offer Type               10910 non-null  object
 21  Sales Channel                  10910 non-null  object
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  object
 24  Vehicle Size                   10288 non-null  object
 25  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [7]:
df.describe()

,Unnamed: 0,Customer Lifetime Value,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Total Claim Amount
count,10910.000000,10910.000000,10910.000000,10910.000000,10277.000000,10910.000000,10277.000000,10910.000000,10910.000000
mean,5454.500000,8018.241094,37536.284785,93.196059,15.149071,48.091934,0.384256,2.979193,434.888330
std,3149.590053,6885.081434,30359.195670,34.442532,10.080349,27.940675,0.912457,2.399359,292.180556
min,0.000000,1898.007675,0.000000,61.000000,0.000000,0.000000,0.000000,1.000000,0.099007
25%,2727.250000,4014.453113,0.000000,68.000000,6.000000,24.000000,0.000000,1.000000,271.082527
50%,5454.500000,5771.147235,33813.500000,83.000000,14.000000,48.000000,0.000000,2.000000,382.564630
75%,8181.750000,8992.779137,62250.750000,109.000000,23.000000,71.000000,0.000000,4.000000,547.200000
max,10909.000000,83325.381190,99981.000000,298.000000,35.000000,99.000000,5.000000,9.000000,2893.239678

In [8]:
df.value_counts()

Unnamed: 0  Customer  State       Customer Lifetime Value  Response  Coverage  Education             Effective To Date  EmploymentStatus  Gender  Income  Location Code  Marital Status  Monthly Premium Auto  Months Since Last Claim  Months Since Policy Inception  Number of Open Complaints  Number of Policies  Policy Type     Policy        Renew Offer Type  Sales Channel  Total Claim Amount  Vehicle Class  Vehicle Size  Vehicle Type
2           LZ68649   Washington  14947.917300             No        Basic     Bachelor              2/10/11            Employed          M       22139   Suburban       Single          100                   34.0                     31                             0.0                        2                   Personal Auto   Personal L3   Offer3            Call Center    480.000000          SUV            Medsize       A               1
7450        TT20057   Oregon      10592.587530             No        Extended  College               1/9/11             Employed          M       59590   Urban          Divorced        136                   15.0                     67                             0.0                        5                   Personal Auto   Personal L1   Offer1            Branch         460.266881          SUV            Small         A               1
7463        TG57800   Oregon      2600.641181              No        Basic     College               1/13/11            Unemployed        F       0       Suburban       Single          74                    19.0                     4                              0.0                        1                   Personal Auto   Personal L2   Offer1            Call Center    501.472124          Two-Door Car   Medsize       A               1
7461        LJ59940   Nevada      16468.220790             Yes       Basic     High School or Below  1/27/11            Unemployed        F       0       Suburban       Divorced        63                    4.0                      52                             0.0                        2                   Corporate Auto  Corporate L3  Offer2            Agent          685.126940          Four-Door Car  Medsize       A               1
7460        ZA83961   Washington  12682.250690             No        Extended  High School or Below  1/20/11            Employed          M       75203   Suburban       Single          80                    0.0                      13                             1.0                        2                   Corporate Auto  Corporate L2  Offer1            Call Center    384.000000          Four-Door Car  Medsize       A               1
                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
3775        LN37854   Arizona     18399.827840             No        Basic     College               2/22/11            Unemployed        F       0       Suburban       Single          73                    33.0                     8                              0.0                        2                   Personal Auto   Personal L1   Offer2            Call Center    525.600000          Four-Door Car  Small         A               1
3777        LZ89104   Oregon      7143.035873              No        Extended  High School or Below  2/23/11            Employed          M       59789   Suburban       Married         90                    9.0                      81                             0.0                        3                   Personal Auto   Personal L3   Offer4            Agent          527.539078          Four-Door Car  Large         A               1
3778        WZ61178   California  5227.230377              No        Basic     Bachelor              1/5/11             Medical Leave     F       11896   Suburban       Married         69                    29.0                     57                             0.0                        5                   Personal Auto   Personal L2   Offer1            Branch         476.254583          Two-Door Car   Small         A               1
3780        PX90263   Oregon      5121.563312              No        Basic     High School or Below  2/19/11            Unemployed        M       0       Suburban       Single          72                    2.0                      22                             0.0                        5                   Personal Auto   Personal L3   Offer1            Branch         518.400000          Four-Door Car  Medsize       A               1
10908       WA60547   California  11971.977650             No        Premium   College               2/13/11            Employed          F       64195   Urban          Divorced        158                   0.0                      27                             4.0                        6                   Personal Auto   Personal L1   Offer1            Branch         618.288849          SUV            Medsize       A               1
Name: count, Length: 4543, dtype: int64

In [9]:
df.shape

(10910, 26)

In [10]:
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].unique()) # Mostra els valors sense repetir
    print("-" * 20)

Column: Unnamed: 0
[    0     1     2 ... 10907 10908 10909]
--------------------
Column: Customer
['DK49336' 'KX64629' 'LZ68649' ... 'KX53892' 'TL39050' 'WA60547']
--------------------
Column: State
['Arizona' 'California' 'Washington' 'Oregon' nan 'Nevada']
--------------------
Column: Customer Lifetime Value
[ 4809.21696   2228.525238 14947.9173   ...  5259.444853 23893.3041
 11971.97765 ]
--------------------
Column: Response
['No' 'Yes' nan]
--------------------
Column: Coverage
['Basic' 'Extended' 'Premium']
--------------------
Column: Education
['College' 'Bachelor' 'High School or Below' 'Doctor' 'Master']
--------------------
Column: Effective To Date
['2/18/11' '1/18/11' '2/10/11' '1/11/11' '1/17/11' '2/14/11' '2/24/11'
 '1/19/11' '1/4/11' '1/2/11' '2/7/11' '1/31/11' '1/26/11' '2/28/11'
 '1/16/11' '2/26/11' '2/23/11' '1/15/11' '2/2/11' '2/15/11' '1/24/11'
 '2/21/11' '2/22/11' '1/7/11' '1/28/11' '2/8/11' '2/12/11' '2/20/11'
 '1/5/11' '2/19/11' '1/3/11' '2/3/11' '1/22/11' '1/23/11' '2/5/11'
 '2/13/11' '1/25/11' '2/16/11' '2/1/11' '1/27/11' '1/12/11' '1/20/11'
 '2/6/11' '2/11/11' '1/21/11' '1/29/11' '1/9/11' '2/9/11' '2/27/11'
 '1/1/11' '2/17/11' '2/25/11' '1/13/11' '1/6/11' '2/4/11' '1/14/11'
 '1/10/11' '1/8/11' '1/30/11']
--------------------
Column: EmploymentStatus
['Employed' 'Unemployed' 'Medical Leave' 'Disabled' 'Retired']
--------------------
Column: Gender
['M' 'F']
--------------------
Column: Income
[48029     0 22139 ... 61146 39837 64195]
--------------------
Column: Location Code
['Suburban' 'Urban' 'Rural']
--------------------
Column: Marital Status
['Married' 'Single' 'Divorced']
--------------------
Column: Monthly Premium Auto
[ 61  64 100  97 117  63 154  85 127  62  99  69 116 114  66  73  94 104
 189  74 121 110 111  72 115 159 101  65  82  71 126  68 199  96  67 125
 249 105  92  78  77  79 223 242  70 102 109 107 119 194 113 106 247  80
  86  81  83 122 253 196 132 139  84 130  93 103 112 222 118  88 182 283
  90 128  89 235 190  76  87 133 153 129  98 148 123  91 211 131 108 187
 214 181 173 252  95 124 137 145 188 143 198 138 245 195 186 170 136 161
 157 141 205 271 192 142 140 134 240 185 244 210 184 202 296 213 273 219
 135 169 155 225 266 215 197 256 212 158 180 166 168 183 162 191 179 150
 146 276 165 239 237 193 229 274 207 295 208 172 217 206 201 171 152 156
 174 238 167 151 144 163 287 209 290 220 228 232 178 177 275 176 281 149
 298 255 216 285 226 160 147 254 164 175 297 234 284 204 218 261 231 248
 286 230 268 203]
--------------------
Column: Months Since Last Claim
[ 7.  3. 34. 10. nan  2.  8. 35. 33. 19. 13.  5. 24. 25.  6. 20. 26. 14.
  9. 29. 11.  1. 18. 16. 30. 12.  4. 22. 31. 21. 28. 17. 15. 32. 23. 27.
  0.]
--------------------
Column: Months Since Policy Inception
[52 26 31  3 73 99 45 24  8 29 32 25 28 87 10 74  1 38 58 37  7 80 95 78
 63 27 97 39 11 59 46 62 13 54 51 22 82 91 44 43 76 48 84  6 92 12 61  4
 18 66 70 16 75 34 35 64  9 89  0 60 71 23 55 93  2 67 81 40 57 86 19 72
 69 33 47 42 17 49 21 83 94 30 15 50 53 77 41 90  5 79 56 98 20 88 65 14
 85 96 36 68]
--------------------
Column: Number of Open Complaints
[ 0. nan  3.  1.  2.  4.  5.]
--------------------
Column: Number of Policies
[9 1 2 7 4 3 6 8 5]
--------------------
Column: Policy Type
['Corporate Auto' 'Personal Auto' 'Special Auto']
--------------------
Column: Policy
['Corporate L3' 'Personal L3' 'Personal L2' 'Corporate L2' 'Personal L1'
 'Special L1' 'Corporate L1' 'Special L3' 'Special L2']
--------------------
Column: Renew Offer Type
['Offer3' 'Offer4' 'Offer2' 'Offer1']
--------------------
Column: Sales Channel
['Agent' 'Call Center' 'Branch' 'Web']
--------------------
Column: Total Claim Amount
[292.8      744.924331 480.       ... 273.018929 381.306996 618.288849]
--------------------
Column: Vehicle Class
['Four-Door Car' 'SUV' 'Two-Door Car' 'Sports Car' 'Luxury Car'
 'Luxury SUV' nan]
--------------------
Column: Vehicle Size
['Medsize' 'Small' 'Large' nan]
--------------------
Column: Vehicle Type
[nan 'A']
--------------------

In [12]:
df['State'].value_counts(dropna=False)

State
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
NaN            631
Name: count, dtype: int64

In [14]:
df['State'] = df['State'].fillna('Unknown')
#para no perder los datos que no tienen estado, les asignamos el valor 'Unknown'

In [16]:
df.columns = [col.lower().replace(' ', '_') for col in df.columns]
print(df.columns)

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type'],
      dtype='object')

In [22]:
f_low_claim_yes = df[(df['total_claim_amount'] < 1000) & (df['response'] == 'Yes')].copy()
f_low_claim_yes.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [20]:
print(df['response'].unique())

['No' 'Yes' nan]

In [21]:
print(df['response'].value_counts())

response
No     8813
Yes    1466
Name: count, dtype: int64

In [24]:
df['vehicle_type'].value_counts(dropna=False)

vehicle_type
NaN    5482
A      5428
Name: count, dtype: int64

In [28]:
df_yes = df[df['response'] == 'Yes'].copy()
analysis_mean_yes = df_yes.groupby(['policy_type', 'gender'])[['monthly_premium_auto', 'customer_lifetime_value', 'total_claim_amount']].mean()
analysis_mean_yes

                       monthly_premium_auto  customer_lifetime_value  \
policy_type    gender
Corporate Auto F                  94.301775              7712.628736
               M                  92.188312              7944.465414
Personal Auto  F                  98.998148              8339.791842
               M                  91.085821              7448.383281
Special Auto   F                  92.314286              7691.584111
               M                  86.343750              8247.088702

                       total_claim_amount
policy_type    gender
Corporate Auto F               433.738499
               M               408.582459
Personal Auto  F               452.965929
               M               457.010178
Special Auto   F               453.280164
               M               429.527942

In [38]:
#Aun que las difrencias entre sexos no son destacables, podemos observar que los hombres tienden a tener polizas más bajas que las mujeres, por lo tanto, son un sector menos provechoso que el femenino. Aun así, en "personal autos" podemos ver como, aun pagando menos, reclaman más.

In [30]:
states_count= df.groupby('state')['customer'].count()
states_count

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Unknown        631
Washington     888
Name: customer, dtype: int64

In [32]:
top_states = states_count[states_count > 500]
top_states

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Unknown        631
Washington     888
Name: customer, dtype: int64

In [35]:
clv_analysis = df.groupby(['education', 'gender'])['customer_lifetime_value'].agg(['max', 'min', 'median', 'std'])
clv_analysis

                                     max          min       median  \
education            gender
Bachelor             F       73225.95652  1904.000852  5640.505303
                     M       67907.27050  1898.007675  5548.031892
College              F       61850.18803  1898.683686  5623.611187
                     M       61134.68307  1918.119700  6005.847375
Doctor               F       44856.11397  2395.570000  5332.462694
                     M       32677.34284  2267.604038  5577.669457
High School or Below F       55277.44589  2144.921535  6039.553187
                     M       83325.38119  1940.981221  6286.731006
Master               F       51016.06704  2417.777032  5729.855012
                     M       50568.25912  2272.307310  5579.099207

                                     std
education            gender
Bachelor             F       6614.107319
                     M       6658.460774
College              F       6678.304057
                     M       6716.960507
Doctor               F       6930.556300
                     M       5460.941400
High School or Below F       7497.848501
                     M       7190.619899
Master               F       6621.774653
                     M       7362.156626

In [36]:
clv_analysis = clv_analysis.sort_values(by='median', ascending=False)
print(clv_analysis)

                                     max          min       median  \
education            gender
High School or Below M       83325.38119  1940.981221  6286.731006
                     F       55277.44589  2144.921535  6039.553187
College              M       61134.68307  1918.119700  6005.847375
Master               F       51016.06704  2417.777032  5729.855012
Bachelor             F       73225.95652  1904.000852  5640.505303
College              F       61850.18803  1898.683686  5623.611187
Master               M       50568.25912  2272.307310  5579.099207
Doctor               M       32677.34284  2267.604038  5577.669457
Bachelor             M       67907.27050  1898.007675  5548.031892
Doctor               F       44856.11397  2395.570000  5332.462694

                                     std
education            gender
High School or Below M       7190.619899
                     F       7497.848501
College              M       6716.960507
Master               F       6621.774653
Bachelor             F       6614.107319
College              F       6678.304057
Master               M       7362.156626
Doctor               M       5460.941400
Bachelor             M       6658.460774
Doctor               F       6930.556300

In [37]:
#Podemos ver que los valores de min y max son más bajos en M que en F, pero que la median es más alto en M. Para poder entender este dato hemos calculado también la "std" y hemos visto como la dispersión en mujeres es mucho más amplia,. Podemoc conluir que la mayoria de hombre estan más concentrados en una mayor cantidad, pero menos representados en los extremos. Eso nos podría llevar a intentar hacer un marqueting más estándar para hombres y más especifico para mujer, debido a su alta dispersión.